server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /price {
    return 301 /price/;
  }

  location /price/ {
    rewrite ^/price/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }
}
